## Numpy
numpy is a python's package for doingmath that is more advanced than +-*/.

this include functions like cosine exponential and squareroot...

on top of this we can use numpy to generate samples for many types of random variables

numpy also have a powerful data type to define vector, matricies and tensors

with these data types numpy also allows us to do linear algebra - matrix-multiplication and matrix vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting list
# this is a vector
vec = np.array([1, 2, 3])
print(vec)
# we can create matricies by converting lists of lists
mat = np.array([[1, 2, 1], [4, 5, 9], [1, 8, 9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0, 15)
print(vec2)
print('')
vec3=np.arange(3, 21, 6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0, 15)
print(vec2)
# print('')
vec3=np.arange(3, 21, 6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  9 15]


In [6]:
# in numpy np.linspace it is a numpy function where we have to pass three parameters in that 
# for example
vec4 = np.linspace(0, 5, 10)
# here np.linspace(0, 5, 10) 0 and 5 both the elements are inclusive and here 10 specifies that including 0 and 5 we mark 10 points
print(vec4)
print('')
print(vec4.reshape(5, 2)) #(i, j) i.e., 5 horizontal rows and 2 vertica columns

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [44]:
# linspace is a method which will give us [p3] points. Points will include [p1] and [p3]
# syntax --> np.linspace(p1, p2, p3)

vec4 = np.linspace(0, 5, 10)
print(vec4)
print('')
print(vec4.reshape(5, 2))
print('')
vec4_reshaped = vec4.reshape(5, 2)
print(vec4_reshaped)
print('')
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [8]:
vec5 = np.arange(0, 12)
vec6 = vec5.reshape(4, 3)
print(vec6)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
mat2 = np.zeros([5, 3])
print(mat2)
mat3 = np.ones([3, 5])
print('') # used for enter or a line space between two lines
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
vec7 = np.arange(1, 6)
vec8 = np.arange(3, 8)
print(vec7)
print('')
print(vec8)
print('')
print(vec7 + vec8)
print('')
print(vec7 * vec8)
print('')
print(1/vec7)
print('')
print(np.sqrt(vec8))

[1 2 3 4 5]

[3 4 5 6 7]

[ 4  6  8 10 12]

[ 3  8 15 24 35]

[1.         0.5        0.33333333 0.25       0.2       ]

[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [11]:
# we can do matrix multiplication by [np.matmul(mat[p1], vec[p2])]
print(mat)
print('')
print(vec)
print('')
product = np.matmul(mat, vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [12]:
print(np.linalg.solve(mat, product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [13]:
# we can find unique values in array
vec9 = np.array(['blue', 'red', 'orange', 'purple', 'purple', 'orange', 'Red', 6])
print(vec9)
print(np.unique(vec9))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [14]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5, 5) #uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10, 5) #standard normal random variable
print('')
print(rand_mat2)

[[0.63873213 0.08743931 0.68049776 0.01872565 0.52460384]
 [0.66825456 0.22848056 0.09490339 0.80993957 0.0859702 ]
 [0.98924489 0.8818624  0.53633425 0.76916981 0.58910499]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

[[-1.83843456 -0.53191667  0.81004922  0.61520781  1.54005593]
 [-0.13952177  0.86869515 -0.32003926 -1.16984612 -0.70826826]
 [-0.63920301  0.49328531 -0.53481833 -0.56665943 -0.74996549]
 [ 1.23551594 -0.32509051  0.0360156  -2.1544921   0.41092446]
 [-4.09786885  0.06614997 -0.56081793 -1.97681802  1.61724669]
 [ 0.6510299   1.00285711  0.07419135 -0.21801023  0.58343801]
 [-1.26834558  0.52460601 -0.12814393  0.80806384 -0.40342443]
 [ 2.20188858 -0.72986656 -1.7056969   1.13112775  0.5355598 ]
 [-0.77963068 -0.77712785 -0.9925865  -0.66728535 -1.30968025]
 [-1.09038537 -0.15108762  1.13078571 -0.4003506  -0.59723415]]


In [15]:
# we can also use numpy for statistical tools on array
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5090283897019895
1.1042644173218217


In [16]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.01872565350713551
2.201888582831358


In [17]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print('')
print(rand_vec[6])

[ 1.18990158e-03 -1.37250608e-01  4.27301846e-02  7.87430306e-01
 -5.71862015e-01 -8.54015534e-01 -1.30783241e+00  1.08659092e-01
 -2.06988974e+00 -7.29072482e-01 -1.34737513e-01 -2.07356625e-01
 -5.76575274e-02  6.62266326e-01  1.54688584e+00 -3.93125562e-01
  4.07408713e-01  7.42348713e-01  1.44272549e+00]

-1.3078324140082853


In [18]:
# we can access multiple entries at once using :
print(rand_vec[4 : 9])

[-0.57186201 -0.85401553 -1.30783241  0.10865909 -2.06988974]


In [19]:
# we can also access multiple non-consecutive entries using arange
print(np.arange(0, 15, 3))
print(rand_vec[np.arange(0, 15, 3)])

[ 0  3  6  9 12]
[ 1.18990158e-03  7.87430306e-01 -1.30783241e+00 -7.29072482e-01
 -5.76575274e-02]


In [20]:
# what about matrices
print(rand_mat)
print('')
print(rand_mat[1][2]) # second row and third column
print('')
print(rand_mat[1, 2])

[[0.63873213 0.08743931 0.68049776 0.01872565 0.52460384]
 [0.66825456 0.22848056 0.09490339 0.80993957 0.0859702 ]
 [0.98924489 0.8818624  0.53633425 0.76916981 0.58910499]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

0.09490339214955401

0.09490339214955401


In [21]:
print(rand_mat[0:2, 1:3])

[[0.08743931 0.68049776]
 [0.22848056 0.09490339]]


In [22]:
# let us change some values in an array
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1, 2]
print('')
print(rand_vec)

[ 1.18990158e-03 -1.37250608e-01  4.27301846e-02  7.87430306e-01
 -5.71862015e-01 -8.54015534e-01 -1.30783241e+00  1.08659092e-01
 -2.06988974e+00 -7.29072482e-01 -1.34737513e-01 -2.07356625e-01
 -5.76575274e-02  6.62266326e-01  1.54688584e+00 -3.93125562e-01
  4.07408713e-01  7.42348713e-01  1.44272549e+00]

[ 1.18990158e-03 -1.37250608e-01  4.27301846e-02  4.00000000e+00
  4.00000000e+00 -8.54015534e-01 -1.30783241e+00  1.08659092e-01
 -2.06988974e+00 -7.29072482e-01 -1.34737513e-01 -2.07356625e-01
 -5.76575274e-02  6.62266326e-01  1.54688584e+00 -3.93125562e-01
  4.07408713e-01  7.42348713e-01  1.44272549e+00]

[ 1.18990158e-03 -1.37250608e-01  4.27301846e-02  1.00000000e+00
  2.00000000e+00 -8.54015534e-01 -1.30783241e+00  1.08659092e-01
 -2.06988974e+00 -7.29072482e-01 -1.34737513e-01 -2.07356625e-01
 -5.76575274e-02  6.62266326e-01  1.54688584e+00 -3.93125562e-01
  4.07408713e-01  7.42348713e-01  1.44272549e+00]


In [23]:
print(rand_mat)
rand_mat[1:3, 3:5] = 0
print('')
print(rand_mat)

[[0.63873213 0.08743931 0.68049776 0.01872565 0.52460384]
 [0.66825456 0.22848056 0.09490339 0.80993957 0.0859702 ]
 [0.98924489 0.8818624  0.53633425 0.76916981 0.58910499]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

[[0.63873213 0.08743931 0.68049776 0.01872565 0.52460384]
 [0.66825456 0.22848056 0.09490339 0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]


In [24]:
# we are adding the columns present at index number 0, index number 1 and index number 2 
# and rows at index no 0 and index no 1 (these we are adding to sub_mat from rand_mat)
sub_mat = rand_mat[0:2, 0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.63873213 0.08743931 0.68049776]
 [0.66825456 0.22848056 0.09490339]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]


In [26]:
sub_mat2 = rand_mat[0:2, 0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print('')
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]


# test your understanding 

In [27]:
vec = np.arange(10,20)
vec2 = vec[np.arange(0, 10, 3)]
print(vec2)

[10 13 16 19]


# Saving and loading numpy arrays



In [29]:
# we can also access entries with logicals

rand_vec = np.random.randn(15)

print(rand_vec)
print('')
print(rand_vec>0)
print('')
print(rand_vec[rand_vec>0])

[ 1.0594263  -0.42448154  0.13674366  0.4378931   1.34876969  0.93312348
  1.61597481  0.07604586 -0.42661076 -0.57254958 -0.40101422 -1.01575721
  0.06815247 -1.12433519  0.17487116]

[ True False  True  True  True  True  True  True False False False False
  True False  True]

[1.0594263  0.13674366 0.4378931  1.34876969 0.93312348 1.61597481
 0.07604586 0.06815247 0.17487116]


In [31]:
print(rand_mat2)
print('')
print(rand_mat2[rand_mat2>0])

[[-1.83843456 -0.53191667  0.81004922  0.61520781  1.54005593]
 [-0.13952177  0.86869515 -0.32003926 -1.16984612 -0.70826826]
 [-0.63920301  0.49328531 -0.53481833 -0.56665943 -0.74996549]
 [ 1.23551594 -0.32509051  0.0360156  -2.1544921   0.41092446]
 [-4.09786885  0.06614997 -0.56081793 -1.97681802  1.61724669]
 [ 0.6510299   1.00285711  0.07419135 -0.21801023  0.58343801]
 [-1.26834558  0.52460601 -0.12814393  0.80806384 -0.40342443]
 [ 2.20188858 -0.72986656 -1.7056969   1.13112775  0.5355598 ]
 [-0.77963068 -0.77712785 -0.9925865  -0.66728535 -1.30968025]
 [-1.09038537 -0.15108762  1.13078571 -0.4003506  -0.59723415]]

[0.81004922 0.61520781 1.54005593 0.86869515 0.49328531 1.23551594
 0.0360156  0.41092446 0.06614997 1.61724669 0.6510299  1.00285711
 0.07419135 0.58343801 0.52460601 0.80806384 2.20188858 1.13112775
 0.5355598  1.13078571]


In [32]:
# we can assign values using logical indexes
print(rand_vec)
print('')
rand_vec[rand_vec > 0.5] = -5
print(rand_vec)

[ 1.0594263  -0.42448154  0.13674366  0.4378931   1.34876969  0.93312348
  1.61597481  0.07604586 -0.42661076 -0.57254958 -0.40101422 -1.01575721
  0.06815247 -1.12433519  0.17487116]

[-5.         -0.42448154  0.13674366  0.4378931  -5.         -5.
 -5.          0.07604586 -0.42661076 -0.57254958 -0.40101422 -1.01575721
  0.06815247 -1.12433519  0.17487116]


In [33]:
# let us save some arrays on the disk to use them later
# np.save --> can save only a single numpy array if we want to save multiple numpy arrays so that we cannot do it.
# np.save(p1,p2) p1--> what will be the name of the saved file. p2--> which one array in particular
np.save('saved_file_name', rand_mat2)

In [34]:
# if we want to save more than one numpy arras we have to use np.savez (z here means zip)
# np.savez(p1,p2,p3....) --> p1(what would be the file name which is to be zipped) 
# p2,p3...(the different arrays which you want to be get zipped)

np.savez('zipped_file_name', rand_mat = rand_mat, rand_mat2 = rand_mat2)
# (rand_mat = rand_mat)the right side one will be  string inside that zipped file. And it is associated with the L.H.S numpy array

In [36]:
# now let us load it

loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.83843456 -0.53191667  0.81004922  0.61520781  1.54005593]
 [-0.13952177  0.86869515 -0.32003926 -1.16984612 -0.70826826]
 [-0.63920301  0.49328531 -0.53481833 -0.56665943 -0.74996549]
 [ 1.23551594 -0.32509051  0.0360156  -2.1544921   0.41092446]
 [-4.09786885  0.06614997 -0.56081793 -1.97681802  1.61724669]
 [ 0.6510299   1.00285711  0.07419135 -0.21801023  0.58343801]
 [-1.26834558  0.52460601 -0.12814393  0.80806384 -0.40342443]
 [ 2.20188858 -0.72986656 -1.7056969   1.13112775  0.5355598 ]
 [-0.77963068 -0.77712785 -0.9925865  -0.66728535 -1.30968025]
 [-1.09038537 -0.15108762  1.13078571 -0.4003506  -0.59723415]]



In [38]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

[[-1.83843456 -0.53191667  0.81004922  0.61520781  1.54005593]
 [-0.13952177  0.86869515 -0.32003926 -1.16984612 -0.70826826]
 [-0.63920301  0.49328531 -0.53481833 -0.56665943 -0.74996549]
 [ 1.23551594 -0.32509051  0.0360156  -2.1544921   0.41092446]
 [-4.09786885  0.06614997 -0.56081793 -1.97681802  1.61724669]
 [ 0.6510299   1.00285711  0.07419135 -0.21801023  0.58343801]
 [-1.26834558  0.52460601 -0.12814393  0.80806384 -0.40342443]
 [ 2.20188858 -0.72986656 -1.7056969   1.13112775  0.5355598 ]
 [-0.77963068 -0.77712785 -0.9925865  -0.66728535 -1.30968025]
 [-1.09038537 -0.15108762  1.13078571 -0.4003506  -0.59723415]]


In [40]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])
print('')

new_array = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

[[-1.83843456 -0.53191667  0.81004922  0.61520781  1.54005593]
 [-0.13952177  0.86869515 -0.32003926 -1.16984612 -0.70826826]
 [-0.63920301  0.49328531 -0.53481833 -0.56665943 -0.74996549]
 [ 1.23551594 -0.32509051  0.0360156  -2.1544921   0.41092446]
 [-4.09786885  0.06614997 -0.56081793 -1.97681802  1.61724669]
 [ 0.6510299   1.00285711  0.07419135 -0.21801023  0.58343801]
 [-1.26834558  0.52460601 -0.12814393  0.80806384 -0.40342443]
 [ 2.20188858 -0.72986656 -1.7056969   1.13112775  0.5355598 ]
 [-0.77963068 -0.77712785 -0.9925865  -0.66728535 -1.30968025]
 [-1.09038537 -0.15108762  1.13078571 -0.4003506  -0.59723415]]

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.   

In [41]:
# we can also save/load as text files... but only single variable
# np.savetxt(p1,p2,p3) --> np.savetxt(file name from which you want to save, array which you want to save, delimeter)
#  delimeter how we can seperate our numpy arrays it is by the delimiters for example by a comma ','

np.savetxt('text_file_name.txt', rand_mat, delimiter = ',')
rand_mat_txt = np.loadtxt('text_file_name.txt', delimiter = ',')

In [42]:
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]

[[3.         3.         3.         0.01872565 0.52460384]
 [3.         3.         3.         0.         0.        ]
 [0.98924489 0.8818624  0.53633425 0.         0.        ]
 [0.99194567 0.66096447 0.18021304 0.91631645 0.22382144]
 [0.62730259 0.1250671  0.17493251 0.53251293 0.68937022]]
