In [1]:
import numpy as np
import pandas as pd

In [2]:
# Q1. Create an array of 8 eights

np.ones(8)*8

array([8., 8., 8., 8., 8., 8., 8., 8.])

In [3]:
# Q2. Create an array of the integers from 10 to 50

arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
# a it is not reshaped so i want to reshape it
arr = np.arange(10, 50).reshape(8, 5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [5]:
# Q3. Create a 3x3 matrix with values ranging from 22 to 30

arr2 = np.arange(22,31).reshape(3, 3)
arr2

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

# use arr3 for the below indexing questions such as q4 and q5

In [6]:
arr3 = np.arange(26,51).reshape(5,5)
arr3
# array([[26, 27, 28, 29, 30],
#        [31, 32, 33, 34, 35],
#        [36, 37, 38, 39, 40],
#        [41, 42, 43, 44, 45],
#        [46, 47, 48, 49, 50]])


array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [7]:
#  Q4. Use indexing on arr3 to get below output
#    [[37, 38, 39, 40],
#    [42, 43, 44, 45],
#    [47, 48, 49, 50]]

arr3[2:, 1:] # (rows, column)

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

In [8]:
# Q5. Use indexing on arr3 to get below output
# Output should be 50

arr3[4:, 4:]
# print(a)

array([[50]])

In [9]:
# Q6. Use indexing on arr3 to get below output
#   [[27], --> (0,1)
#    [32], -->  (1,1)
#    [37]]  --> (2,1)

arr3[0:3, 1:2]

array([[27],
       [32],
       [37]])

In [10]:
# Q7. Use indexing on arr to get below output
#   [46, 47, 48, 49, 50]
    
arr3[4:,]

array([[46, 47, 48, 49, 50]])

In [11]:
# Q8. Use indexing on arr to get below output
#  [[41, 42, 43, 44, 45],
#    [46, 47, 48, 49, 50]]

arr3[3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [12]:
# Q9. Find the sum of all the values in given array 'arr4'
arr4 = np.arange(10,40).reshape(6,5)
arr4

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [13]:
np.sum(arr4)

735

In [14]:
# Q10. Find the standard deviation of the values in given array 'arr4'
np.std(arr4)

8.65544144839919

In [15]:
# Q10. Find the mean of the values in given array 'arr4'
np.mean(arr4)

24.5

## now we will practice Pandas 

In [16]:
df = pd.read_csv("sales.csv")

In [17]:
print(df)

     Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0              1     9796.0       5250.0     10703.0      1659.0   
1              2     8294.0       8186.0     12694.0      1461.0   
2              3    11001.0      14399.0     16991.0      1340.0   
3              4     8301.0      11188.0     12289.0      1451.0   
4              5    10510.0      12629.0     13921.0      1770.0   
..           ...        ...          ...         ...         ...   
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0             1961.0          Open           CAT B                   530   
1             1752.0  Not Provi

In [18]:
# Q1. What are the unique values in the column "Parking"?
# SYNTAX --> df['column_name'].unique()

df['Parking'].unique()

array(['Open', 'Not Provided', 'Covered', 'No Parking'], dtype=object)

In [19]:
# Q2. What is the mean store area of the given data?

df['Store_Area'].mean()

1511.862554112554

In [20]:
# Q3. What are the different columns available in the dataset?

df.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

In [21]:
# Q4. Create a new series (series1) with only the values of third row
# df.iloc[row_index]

df.iloc[2]

Observation                        3
Dist_Taxi                    11001.0
Dist_Market                  14399.0
Dist_Metro                   16991.0
Store_Area                    1340.0
Items_Available               1609.0
Parking                 Not Provided
Coupon_Category                CAT A
Daily_Customer_Count             720
Store_Sales                    54010
Name: 2, dtype: object

In [22]:
# Q5. Create a new dataframe(df_short which contain first 5 rows and two columns("Coupon_Category" and "Store_Sales")

df_short=df.loc[[0,1,2,3,4],["Coupon_Category","Store_Sales"]]
df_short

Coupon_Category  Store_Sales
0           CAT B        66490
1           CAT B        39820
2           CAT A        54010
3           CAT B        53730
4           CAT B        46620

In [23]:
# Q5 also be done as or presented as


df.head(5)[["Coupon_Category","Store_Sales"]]

Coupon_Category  Store_Sales
0           CAT B        66490
1           CAT B        39820
2           CAT A        54010
3           CAT B        53730
4           CAT B        46620

In [24]:
# Q6. In dataframe df_short, replace the index with ["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]

df_short["Names"] = ["First_row", "Second_row", "Third_row", "forth_row", "fifth_row"]
df_short

Coupon_Category  Store_Sales       Names
0           CAT B        66490   First_row
1           CAT B        39820  Second_row
2           CAT A        54010   Third_row
3           CAT B        53730   forth_row
4           CAT B        46620   fifth_row

In [25]:
df_short.set_index("Names", inplace = True)
df_short

Coupon_Category  Store_Sales
Names                                  
First_row            CAT B        66490
Second_row           CAT B        39820
Third_row            CAT A        54010
forth_row            CAT B        53730
fifth_row            CAT B        46620

In [26]:
# Q7. Create a dataframe df2 fulfilling the given conditions - Dist_Metro>18000 and Parking= Open

df2 = df[(df["Dist_Metro"]>1800) & (df["Parking"] == "open")]
df2

Empty DataFrame
Columns: [Observation, Dist_Taxi, Dist_Market, Dist_Metro, Store_Area, Items_Available, Parking, Coupon_Category, Daily_Customer_Count, Store_Sales]
Index: []

In [27]:
# Q8. What is the minimum store sales and the standard Deviation of store sales.

df_short['Store_Sales'].min()



39820

In [28]:
df_short['Store_Sales'].std()

9927.236775659176

In [29]:
# Q9. Group the dataset with respect to the variable 'Coupon_Category' using aggregation function mean().



In [38]:
# Q10. Drop the variable 'Parking' from the data.
# syntax --> df. drop('A', axis=1) .

df.drop("Parking", axis = 1)


Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0              1     9796.0       5250.0     10703.0      1659.0   
1              2     8294.0       8186.0     12694.0      1461.0   
2              3    11001.0      14399.0     16991.0      1340.0   
3              4     8301.0      11188.0     12289.0      1451.0   
4              5    10510.0      12629.0     13921.0      1770.0   
..           ...        ...          ...         ...         ...   
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available Coupon_Category  Daily_Customer_Count  Store_Sales  
0             1961.0           CAT B                   530        66490  
1             1752.0           CAT B                   210        39820  
2             1609.0           CAT A                   720        54010  
3             1748.0           CAT B                   620        53730  
4             2111.0           CAT B                   450        46620  
..               ...             ...                   ...          ...  
927           1910.0           CAT C                  1080        66390  
928           1663.0           CAT A                   850        82080  
929           1436.0           CAT A                  1060        76440  
930           1560.0           CAT B                   770        96610  
931           1429.0           CAT C                  1110        54340  

[932 rows x 9 columns]

In [39]:
print(df)


     Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0              1     9796.0       5250.0     10703.0      1659.0   
1              2     8294.0       8186.0     12694.0      1461.0   
2              3    11001.0      14399.0     16991.0      1340.0   
3              4     8301.0      11188.0     12289.0      1451.0   
4              5    10510.0      12629.0     13921.0      1770.0   
..           ...        ...          ...         ...         ...   
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0             1961.0          Open           CAT B                   530   
1             1752.0  Not Provi

In [41]:
# df_short("Parking", axis = 1)

In [42]:
# Q11. Export the Q10 dataframe without the 'Parking' column into a csv file.

